spring:
  application:
    name: DATA-INTEGRATE-WEB
eureka:
  instance:
      hostname: ${spring.application.name}
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8079/eureka/
server:
  port: 8080