spring:
  application:
    name: DATA-INTEGRATE-EUREKA
eureka:
  instance:
      hostname: ${spring.application.name}
      preferIpAddress: true
  #server:
    #enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8079/eureka/
server:
  port: 8079